services:
  web1:
    image: nginx
    container_name: 'web1'
    volumes:
      - ./web1:/usr/share/nginx/html
    ports:
      - 5000:80

  web2:
    image: nginx
    container_name: 'web2'
    volumes:
      - ./web2:/usr/share/nginx/html
    ports:
      - 5001:80

  reverse_proxy:
    image: nginx
    container_name: 'reverse_proxy'
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
